plugins:
  eslint:
    enabled: true
    channel: eslint-6
    config:
      config: ./.eslintrc.json

exclude_patterns:
  - "**/*spec.ts"
  - "**/*e2e-spec.ts"
  - "**/*uniqueIdGenerator.ts"
  - "*/**/scripts/*"
  - "*/**/migration/*"
